---
title             : "**Pride and Protest: Emotional response in the aftermath of the Chilean social outburst**"
shorttitle        : "Pride and Protest"

author: 
  - name          : "Francisco Olivos"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Room 424, Sino Building, The Chinese University of Hong Kong, Shatin, Hong Kong"
    email         : "fjolivos@link.cuhk.edu.hk."
  - name          : "Cristián Ayala"
    affiliation   : "2"
  - name          : "Alex Leyton"
    affiliation   : "2"
    
affiliation:
  - id            : "1"
    institution   : " The Chinese University of Hong Kong, Department of Sociology"
  - id            : "2"
    institution   : "Pontificia Universidad Católica de Chile, DESUC"

authornote: |
  The authors thank Fundación Imagen de Chile for facilitating the access to the data. They also thank XXXX for their fruitful comments and suggestions on preliminary versions of this article. Francisco Olivos acknowledges the support of the Hong Kong Ph.D. Fellowship Scheme.

abstract: |
  In the last months, Chile -like others in the world- has gone through an environment of widespread street protests claiming for structural changes and challenging the "Chilean miracle". This study uses an interrupted public opinion poll to assess the effect of the Chilean social crisis that began in October 2019 on moral sentiments of the general population. Our findings suggest that emotions toward the country, symbols, and economic development were negatively affected by the crisis. Protests signaled that the system was not as it was thought, generating a moral shock that affected shared feelings and beliefs about the country. However, at the same time, the specific reciprocal moral sentiments between citizens themselves were positively affected. Henceforth, the social crisis emerges as an opportunity for strengthening collective ties either by sharing sentiments toward who is blamed by the movement or between Chileans. It is important to notice that the general sentiment toward citizenship is not affected. In the aftermath of October 18, the "unsettled times" have created a burst of potential cultural changes, albeit their stability, in the long run, is still uncertain. 
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "social movements, emotions, Chile, public opinion, cultural change"
wordcount         : "5889"

bibliography      : ["socious.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
#output            : papaja::apa6_word
header-includes:
  - \usepackage[document]{ragged2e}
---

Introduction 
---------------------------------------------------------------------------------------

Recent developments in cultural sociology suggest that cultural change is rather the exception than the norm [@Kiley2020; @Vaisey2016]. Either cultural change occurs due to cohort replacement [@Vaisey2016], or changes are non-persistent [@Kiley2020].  This perspective does not provide hopeful expectations in the current context where climate change, the pandemic of coronavirus disease, and widespread socio-political crises arise uncertainties about future directions of our systems of values and traditional forms of culture. All these events could be understood as moral shocks [@Jasper2011; @Jasper1998] that could have consequences in the way that we feel and think, breaking with the stability of cultural dispositions and belief systems. In this study, we attempt to examine the short-term effects of one of these shocks on moral emotions and discuss whether it lays the foundations for a more stable cultural change.

After the revival of emotions in the cultural analysis of protests [@Goodwin2000; @Jasper2011; @Jasper1998; @Jasper2014], they have been isolated as causal mechanisms of willingness or actual engagement in social movements [e.g. @DeCelles2019; @Thomas2020; @Weber2002]. However, the literature on the effect of protests on emotions has not followed the same pace. Using an interrupted public opinion poll, we analyze the impact of the "Chilean spring" of 2019 [@Somma2020] on the pride about the country, beliefs about economic development, and beliefs about Chilean citizens. We conceptualize these aspects of culture as moral sentiments in the framework of emotions of protest [@Jasper2011]. The Chilean social outburst^[Translation given to the term "estallido social" [@Somma2020] used by the media and public opinion in reference to the protests in Chile.] is a case in a multicausal global wave of protests. Hong Kong, Lebanon, Catalonia, and, more recently, the United States have encountered massive social movements^[For the sake of simplicity, we use the terms social movement, protests movement, and protests interchangeably. For a discussion, see [@Jasper2014].] in the last months, and some are still ongoing at the moment of writing. The "Chilean spring" offers an opportunity to evaluate the changes in feelings and beliefs of the general population after the first weeks of protest activities, which we refer to as short-term consequences of the social movement. Chile was the first neoliberal experiment that later would be expanded around the world [@Harvey2007], and this movement has signaled deficiencies of the model. Therefore, the protests in Chile do not only defy the structural conditions of the country, but rather the global economic system. As Fantasia and Hirsch [-@Fantasia2004] argue, acute social struggles provide bases for cultural transformation. The Chilean social outburst initiated what cultural sociologists [@Swidler1986; @Bail2012] have called "unsettled times," where the large-scale and unprecedented crisis challenges shared beliefs about how society should work.

Since early October of 2019, secondary-school students started protesting fare-dodging on the metro of Santiago, capital of Chile, after an increase of the fare from about USD 1.12 to USD 1.16, equivalent to 0.28 percent of the minimum wage [@Gonzalez2020]. Protests involving students have been commonplace in Chile's political landscape since the so-called "penguin revolution" [@Donoso2013;@Guzman-Concha2012]. However, on October 18, everything changed, and protests escalated to the general population^[For a more detailed description of the context and main facts of the social crisis in Chile, as well as explanations based on survey data fielded during the crisis see [@Gonzalez2020].]. Barricades were built, the entire metro system was shut down after attacks, and stations were set alight. On October 19, protests continued across the country with shops looted, buses burned, and clashes between protestors and the special police forces. The government declared an emergency state and curfew. Several international organizations have reported human rights violations during that time [e.g. @UnitedNations2019]. Although the protests have been sporadic during the coronavirus pandemic, and all the spectrum of political parties has approved a referendum for a new political constitution, the case of Hong Kong [@Wang2020] provides signals that the Chilean movement could also be resumed after the health emergency is under control. 

As a shared feature of unsettled times and turning points [@Abbott1997; @Bail2012], social scientists and policymakers convey that the escalation of the events in Chile on October 18 was unexpected or "they did not see it coming" [e.g. @Sanhueza2019; @Somma2020]. However, its underlying causes are still a matter of debate. The low levels of political identification, distrust in political parties, unfulfilled expectations, cultural change, and market-based inequalities, among others, have been suggested [e.g. @Gonzalez2020; @Somma2020]. Although citizens claim for deep structural reforms (e.g. changes in the pension system, reform of the police, a new political constitution), Chile has been long considered one of the most developed countries of Latin America. In the last three decades, Chile has undergone unprecedented changes: reduction of poverty, increased GDP, and longer life expectancy [@TheWorldBank2017]. Hence, this article compares moral sentiments before and after the unexpected events of the first weeks of the Chilean protests movement. Coincidently, the social crisis interrupted the fieldwork of a public opinion poll aimed to measure beliefs and attitudes toward the country [@ImagenPais2019]. Thus, this survey provides a unique opportunity to examine the effects of the "Chilean spring" as a moral shock.   

Following the literature in emotions and social movements, the Chilean social outburst could be conceptualized as a moral shock [@Jasper2011; @Jasper1998; @Jasper2014] that provided information signaling that the country was not as expected, leading to the re-articulation of emotions and beliefs about the country and citizens themselves. Our findings indicate that the protests negatively affected the national pride and beliefs about development but increased the positive valuation of characteristics of Chileans. 

The contribution to the literature is threefold. First, this study is one of the first in providing robust evidence of the consequences of the protests in the "Chilean spring," which is part of a larger and dynamic ongoing wave of protests in the world. Second, in the last decades, the literature in emotions has taught us much about why people protest [@VanStekelenburg2013]. However, there are few studies considering its cultural consequences on citizens. Third, social and political psychologists have provided evidence of the role of emotions using lab experiments. However, although their internal validity, these studies lack ecological validity [@VanStekelenburg2013], and researchers do not really know if the students in the lab are willing to take the streets. Besides defining emotions as an outcome, we use a public opinion survey applied to the general population before and after the protests outburst. Therefore, our findings are sustained on more realistic grounds.

The article is structured as follows. First, the theoretical framework of emotions and social movements is discussed, which provides tools to understand the social outbreak as a moral shock. Second, in the methodological section, data, measurements, and analytical strategy are presented in detail. Third, the results are reported and discussed in the conclusion.  

Protests and emotional response
---------------------------------------------------------------------------------------


The aftermath of the 18-O could be understood as an unexpected moral shock of the Chilean society. The widespread protests along the country signaled that the Chilean case's apparent success was not as expected. According to Jasper [-@Jasper2011], these moral shocks generate vertiginous feelings, a rethinking of moral principles, restructuration of worldviews, or activation of underlying values. In addition, repression events following protests -as the case of the protest movement in Chile [@Somma2020]- could lead to even greater mobilization and ignite public indignation toward the responsible of the repression [@Aytac2018; @Hess2006]. Thus, the moral shock is stronger.  

Emotions are an aspect of culture [@Jasper2014]. Culture delineates how emotions are constituted, managed, and experienced [@Thoits1989]. In toolkit theory, culture is strategically used to make-sense and justify actions [@Swidler1986; @Vaisey2009]. For instance, people use different understandings of love to interpret their circumstances, feelings, and beliefs [@Swidler2001]. Emotions also participate in the reproduction of culture, subjectivity, and power relations [@Harding2002], linking cognitive understandings and action. 

Jasper [-@Jasper2006] has integrated different emotions in the literature into a typology, which helps us to define clearly the scope of this study. First, reflex emotions are quick and automatic reactions to certain events. They include anger, joy, distrust, fear, among others. Second, moods which are typically lasting longer than reflex emotions. They do not take direct objects and can be deployed across settings. For instance, nostalgia. Third, moral sentiments are more complex than the previous ones. They are more stable feelings toward others or objects and include pride and shame, but also compassion, outrage, and complex forms of fear and anger. When these moral sentiments include support for changes in the structure of the society, they are part of what has been termed "sentiment pools" [@Kim2016], which are crucial for the effectivenes and success of social movements [@Bugden2020]. Moral sentiments could be also considered as part of the "hot cognition" [@Gamson1992] that triggers political consciousness and participation. Social movements research indicates that the achievement of their goals and social change depend upon the support from the public and the aligment of shared sentiments [@Andrews2016;@Snow1986]. Our survey includes measurements of moral sentiments, which are detailed in the variables section. 

Social problems that protests signal also require someone to be held accountable [@Jasper2014]. In the case of Chile, the government and the economic system has been blamed as responsible. Thus, the indignation is targeted toward the government, the system, and their symbols. These moral sentiments are shared by participants and supporters of the social movements. As shown by other public opinion polls, a large majority of the Chilean population supported and participated in the movement across the country^[Based on a representative and probabilistic sample, surveys [@NucleoMilenioenDesarrolloSocial2019] indicate that 85.5 percent of Chileans over the age of 18 declared their support toward the social movement one month after the social outbreak; 55.3 percent declared to have participated in some form of protest; 70 percent are willing to participate in cabildos cuidadanos (open citizen councils) to discuss the new political constitution and the political context.]. Therefore, these emotions are widely shared by the population and could explain the low levels of approval of the government^[One of the most prestigious public opinion polls [@CentrodeEstudiosPublicos2019] showed that 81 percent of the Chileans consider that the governed responded wrongly or very wrongly to the social outbreak, and the president reached the lowest level of approval (6 percent) since it is historically measured in the country.] . Henceforth, the first expectation is that these negative moral sentiments will be strengthened in the aftermath of the social crisis (hypothesis 1). On the other hand, social movements also generate reciprocal emotions among participants and supporters of the movement. Thus, the positive affections toward citizens might be positively affected by the social outburst (hypothesis 2). The restructuring of negative moral sentiments toward the government and positive moral sentiments toward citizens could have reinforced the collective identity associated with the social movement [@Jasper2011], and explain the scalation that the Chilean crisis took in the months after the night of October 18. We cannot elucidate whether the changes will be a stable cultural transformation, or whether moral sentiments will revert to the baseline. However, if the movement had short-term effects on how citizens feel and think, it could be on the basis of a long-term transformation.  

Data and Methods
---------------------------------------------------------------------------------------

We use data from the Chilean Pride Study [@ImagenPais2019], a stratified and probabilistic sample of 1,503 Chileans over the age of 18 collected using a CATI (computer-assisted telephone survey). The fieldwork started in October 11 of 2019, one week before the outburst the night of October 18. Out of the total sample, 27.8 percent of respondents were surveyed before that night and the remaining 72.5 percent in the upcoming month. The fieldwork was resume on November 5 after the protests began. Thus, it provides unique conditions for evaluating the effect of the first weeks of the protest movement as an events study. The survey was originally intended to examine the beliefs of Chileans about their own country and identity, including questions of substantive relevance for our research problem. 

This data was analyzed as a time series interrupted by the events of the Chilean social crisis that started on October 18. The main methodological challenge of this type of design [e.g. @Minkus2019; @Slothuus2010] is to make sure that respondents interviewed before and after the event are comparable and the difference between treated and controlled could be attributed to the events. Table 1 shows a balancing test for the background characteristrics asked in the survey. Subsamples before and after the social outburst are balanced in terms for gender, age, and number of household members. Nevertheless, there are sligh differences in the geographic zone of the respondents. Respondents from the Metropolitan Region were less (B=-0.052, p<.05) likely to by surveyed when the data collection was resumed due to the organisation of the fieldwork. In contrast, the ex-post sample overrepresents  inhabitants from southern Chile (B=0.054, p<.01). Moreover, there is also a slight positive effect of the treatment on the group of individuals with lower educational level (B=0.047, p<.05). As explained in the analytical strategy, this result suggests the relevance of including these variables as additional covariates and weights in the entropy balance. Table 1S, in the supplementary material, provides a detailed account of occurred events between the interruption of the fieldwork and its resumption. 

\begin{center}
[Table 1 about here]
\end{center}

### Measurements

The impact of the Chilean protests movement is assessed by four moral sentiments toward the country and the system, and three toward the Chilean citizens. 

\textit{Pride in the country}. Respondents were asked how much proud in the country they are in a 7-categories scale, where 1 represents "nothing proud" and 7 "very proud". 

\textit{Pride of being Chilean}.The reciprocal moral sentiments between citizens was measured by a general question about pride in their citizenship. Respondents answered how much proud of being Chilean they are. It uses the same scale than pride in the country.    

The original survey included items measuring how proud the respondent are in especific aspects of the country and citizens. These items are diverse, including, for instance, sky for astronomy, science and technology, and export products. Two of them are of theoretical relevance for this study: \textit{"pride in country's emblem and motto"} and \textit{"the energy of the own people"}. The first is particularly salient for measuring the moral sentiments toward the country and the system. After Pinochet's military dictatorship, Chilean national emblem (Figure 1) has been signified as a symbol of conservative sectors of the society and the military heritage [@Joignant2007]. In addition, the motto in the emblem could be translated as "by reason or force." This phrase as long been considered by neighboring countries as a representation of the Chilean expansionism of the XIX century and the iron fist of the government [@Burr1965]. This indicator contrasts with our second measurement that refers to a feature of Chileans. 

\begin{center}
[Figure 2 about here]
\end{center}

\textit{Pride in the economic development} is measured by a Likert scale. Respondents were asked about their agreement regarding different phrases about Chile. Among them \textit{"Chile is an economically developed and stable country"}. In addition, we also include the agreement with the phrase "Chile is a good place to live." Categories of response range from 1 "strongly disagree" to 7 "strongly agree." Both indicators represent moral sentiments toward the country.  

Finally, respondents were asked \textit{"From the followig statements, which one you whish people outside of the coutry would think about Chileans"}. Respondents could choose among six categories: (1) Chileans are happy and welcoming, (2) Chileans are dedicated and hard-working, (3) Chileans care of their territory and environment, (4) Chileans are serious and responsible, (5) Chileans have high-quality products, and (6) Chile is an economically developed country. The last category is treated as missing because it is unrelated to Chileans' features, and few people choose it (N=12). Based on a multinomial model reported in Table 2S of the supplementary material, we recoded this variable into a dummy indicator of effort where 1 represents "Chileans are dedicated and hard-working" and 0 "otherwise". Additional information is provided in the results section.


### Analytical strategy

Our analytical strategy is threefold. We estimate an OLS regression with the respective emotion as the dependent variable and the treatment dummy (1 "treated" 0 "controlled") as the independent variable. Robust standard errors are included. This model can be formalized as follow:

\begin{equation}
\gamma=\beta_0 + \beta_1 T + \epsilon	
\end{equation}

where $\beta_1$ represents the average treatment of the protests (\textit{T}) on the emotion $\gamma$; $\beta_0$ stands for the intercept and $\epsilon$ error term. In addition, two complementary analyses were conducted as robustness checks. First, control variables were included in the model:

\begin{equation}
\gamma=\beta_0 + \beta_1 T+\beta_2 \delta + \epsilon	
\end{equation}

where $\delta$ stands for a vector of control variables (gender, age, educational level, number of household members, and geographic zone of residence). Second, we used entropy balancing [@Hainmueller2012], which is a matching technique that estimates scalar weights for the treatment group. It calculates balance covariates directly through the exact match of pre-specified means and variances of the covariates' distribution of the treatment and control group [@Hainmueller2012; @Stahl2020]. Unlike other matching techniques, entropy balancing makes treatment orthogonal to these predefined covariates.  


Results
---------------------------------------------------------------------------------------

The effects of the social crisis on moral sentiments are plotted in Figure 2 and Figure 3. Full models could be found in Table 3S and 4S of the supplementary material. They are the main tests of our theoretical predictions. As stated in hypothesis 1, Figure 2 suggests that the protest movement negatively affected moral sentiments toward the country. After the first weeks of the movement, pride in the country (B=-0.519, p<.000), positive beliefs about Chilean economic development (B=-0.500, p<.000), pride in national symbols (B=-0.369, p<.000), and Chile as good place to live (B=-0.248, p<.000) were lower than the baseline. These effects are consistent when using controls and entropy weights, suggesting the robustness of the findings against potential selection into the treatment.

\begin{center}
[Figure 2 about here]
\end{center}

In contrast, Figure 3 shows the oppositive effect on moral sentiments toward citizens. The pride in being Chilean does not vary significatively after the social movement began. However, as predicted in hypothesis 2, there are significant effects on the especific indicators. The social crisis increased the valoration of the citizens themselves. The pride in the energy of Chileans (B=0.247, p<.000) and the valorization of the effort as a feature of the citizens (B=0.072, p<.000) significantly increased after the first weeks of the social movement. Table 2S, in the supplementary material, shows a multinomial model for the effect on features of Chileans. The findings consistently indicate that the valuation of effort as a feature of Chileans is strengthened after the "Chilean spring" began in comparison to all the other measured characteristics with the exception of "Chileans are happy and welcoming".     

\begin{center}
[Figure 3 about here]
\end{center}

A recent study [@Gonzalez2020] has found an association between participation in the Chilean protests and both educational level and age. More educated and younger people were more likely to declared have participated in protest activities. It is consistent with the idea of critical citizens [@Norris1999]. Therefore, we explore whether these groups are also differently affected by the social outburst. Figure 5 indicates that the effects of moral sentiments toward the country are stronger for individuals with intermediate educational level. It could possible capture the heterogeneity of the effect by position in the social structure. Chile is a highly unequal society with high levels of social closure [@Mendez2019], and, although their internal heterogeneity, an important part of the middle class shares the support toward neoliberal policies and the status quo [@Barozet2016; @Barozet2011; @MariaLuisa2008]. For instance, as shown in Figure 5, individuals with complete secondary education are the group with the highest level of national pride before the protests, but equaled the other groups in the aftermath of the first weeks of the crisis. The moral shock could have highlighted the vulnerability of this sector and the new middle class documented by the literature [@Ravallion2009; @Torche2012; @Lopez-Calva2014]. Nevertheless, we do not have direct measurements of social class for a more robust test of this hypothesis. Regarding reciprocate moral sentiments, individuals with less than secondary education exhibit the largest increase in the feature of effort as desirable to define Chileans. As system justification theory states, low status individuals develop this type of beliefs as a psychological mechanism of defense [@Jost2004], and it could have been trigger by the crisis. 

Regarding age, there is no heterogeneity of the effects (models under request). This finding is relevant considering that recent evidence [@Kiley2020] has supported the hypothesis that younger individuals do more active updating of culture than older individuals. In our subset of moral sentiments, both older and younger respondents are sensitive to the moral shock of the social crisis. 


Conclusions
---------------------------------------------------------------------------------------


Chile was the first neoliberal experiment [@Harvey2007]. In the last months, the country -like others in the world- has gone through an environment of widespread street protests claiming for structural changes and challenging the "Chilean miracle" [@Friedman1991]. This study uses an interrupted public opinion poll to assess the effect of the Chilean social crisis that began in October 2019 on moral sentiments of the general population. Our findings suggest that emotions toward the country, symbols, and economic development were negatively affected by the crisis. Protests signaled that the system was not as it was thought, generating a moral shock that affected shared feelings and beliefs about the country. However, at the same time, the specific reciprocal moral sentiments between citizens themselves were positively affected. Henceforth, the social crisis emerges as an opportunity for strengthening collective ties either by sharing sentiments toward who is blamed by the movement or between Chileans. It is important to notice that the general sentiment toward citizenship is not affected. In the aftermath of October 18, the "unsettled times" [@Swidler1986; @Bail2012] have created a burst of potential cultural changes, albeit their stability, in the long run, is still uncertain.  

Although previous studies have shown that social movements have a causal effect on how new cultural elements emerge and develop [e.g. @Isaac2009], recent evidence in cultural sociology has suggested that changes in the belief system come through generational turnover [@Kiley2020; @Vaisey2016], instead of an active updating to the environment. In the subset of beliefs and attitudes studied by this literature, high-salience topics and attitudes toward institutions show evidence of active updating. Moral sentiments toward the system and collective identity measured by our items could be considered among those cultural elements [e.g. @Boutyline2017]. Nevertheless, our findings cannot confirm that the change in moral sentiments will be permanent, rather it provides strong evidence that the social crisis had a "\textit{period effect}" on feelings and worldviews. Cultural change not only trigger the outburst [@Somma2020], but narratives, frames, and worldviews of the general populaton are also affected by the social movement. Thus, the protests movement could offer the basis and tipping point for cultural and social change in the aftermath of a major rupture in contemporary Chilean history. Further studies might examine the durability of these changes. At the same time, the protests continued after data gathering. Therefore, the identified effects also could explain the durability of the movement and massiveness. 

We have not evaluated the effect on reflex emotions or moods [@Jasper2006;@Jasper2011], but in moral sentiments or more long-standing affective commitments, such as pride in the country. Moreover, we do not find changes in the overall sentiment toward citizens but on particular features instead. The general sentiment toward being Chilean is more comprehensive and is at a higher level of abstraction. A mainstream framework in values change [@Flanagan2000;@Flanagan1982;@Rokeach1973] suggests that core beliefs tend to be acquired at an early age and resist change. Thus, we could argue that, in our case, the effect is on more peripherical aspects of the private culture. The moral shock, or at least during the first weeks of protests, was not sufficient to modify this deeper and more enduring belief.      

The limitations of our study are threefold. First, we have been cautious in not referring to our estimations as causal. Our design could resemble a natural experiment, and we compare balanced groups before and after the beginning of the social crisis. However, the original survey was not designed to contain a larger set of measurements to assess other characteristics that could unbalance pre- and post-treatment samples. For instance, prosocial behavior increases the willingness to participate in surveys and shapes attitudes and beliefs [@Groves1992]. Thus, we cannot examine whether individuals with higher pro-social behaviors were overrepresented in the first stage of the survey because they are an easier-to-reach population due to their willingness to participate. Second, we cannot disentangle the specific treatment that generated the change on moral sentiments, or whether they explain it all together. Violations of human rights, media coverage, protests events, President's addresses, among others, could have driven these changes. Therefore, we provide robust evidence of the emotional consequences of the social movement, but without identifying the specific "spark" of this change. The repression by the police in the aftermath is particularly relevant among these factors because it generated fear and anger [@Somma2020]. As Bail [-@Bail2012] suggests, these feelings are emotional energy, enabling civil society to achieve resonance in the public sphere and foster cultural change. And third, the public opinion poll was not designed to measure political engagement, and the questionnaire was not modified after the social crisis. Hence, we cannot identify clearly respondents that participated in activities of protests. Instead, our results refer to an effect on the general population.            

The Chilean case illuminates the understanding of contemporary events around the world. For instance, Hong Kong is currently in the second wave of protests after the pandemic of coronavirus disease has been controlled by the government. Our study could raise the question of whether this movement has affected the moral feelings toward the Chinese government, democratic values, or collective identities. At the same time, the wave of protests in the United States after George Floyd's death could have impacted on attitudes toward racial discrimination and the police. In addition, the key findings speak to social movements motivated by other types of causes. Regarding climate protests [@Bugden2020], their effectiveness relies on the effect on sentiments of support for structural changes generated on the public. Henceforth, what the Chilean case illustrates is that social movements could have important short-term emotional consequences and could lay the foundations for further cultural changes.   


References
---------------------------------------------------------------------------------------

